---
version: '3.8'
services:
  assistant:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    environment:
      - DB_HOST=db
      - REDIS_HOST=cache
      - MODEL_PATH=/models/deepseek-coder
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../../models:/models
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../config/.env

  cache:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
